import { useState } from 'react';
import { api } from '../api';
const label = (status) => status[0].toUpperCase() + status.slice(1);
export default function Admin({ token, users, appointments, refresh, onLogout }) {
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'doctor' }); const [error, setError] = useState('');
  const createUser = async (event) => { event.preventDefault(); try { setError(''); await api('/api/users', { token, method: 'POST', body: form }); setForm({ name: '', email: '', password: '', role: 'doctor' }); await refresh(); } catch (requestError) { setError(requestError.message); } };
  const update = async (id, status) => { try { await api(`/api/appointments/${id}`, { token, method: 'PUT', body: { status } }); await refresh(); } catch (requestError) { setError(requestError.message); } };
  return <main className="dashboard-shell"><header className="dashboard-topbar"><div><p className="eyebrow">Admin Panel</p><h1>QueueCare Dashboard</h1></div><button className="outline-btn" onClick={onLogout}>Logout</button></header><section className="stats-grid"><article className="stat-card"><span>Total Doctors</span><strong>{users.filter((user) => user.role === 'doctor').length}</strong></article><article className="stat-card"><span>Total Patients</span><strong>{users.filter((user) => user.role === 'patient').length}</strong></article><article className="stat-card"><span>Active Queue</span><strong>{appointments.filter((item) => ['pending', 'confirmed'].includes(item.status)).length}</strong></article><article className="stat-card"><span>Completed</span><strong>{appointments.filter((item) => item.status === 'completed').length}</strong></article></section><section className="dashboard-grid"><div className="panel"><div className="panel-heading"><h2>Add User</h2></div>{error && <p className="error-message">{error}</p>}<form className="stacked-form" onSubmit={createUser}><input placeholder="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><input type="email" placeholder="Email address" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><input type="password" placeholder="Password (8+ characters)" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} minLength="8" required /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="doctor">Doctor</option><option value="staff">Staff</option><option value="patient">Patient</option><option value="admin">Admin</option></select><button>Add User</button></form></div><div className="panel wide-panel"><div className="panel-heading"><h2>Appointments</h2></div><div className="table-wrap"><table><thead><tr><th>Token</th><th>Patient</th><th>Doctor</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{appointments.map((item) => <tr key={item._id}><td>{item.tokenNumber}</td><td>{item.patientId?.name}</td><td>{item.doctorId?.name}</td><td>{new Date(item.appointmentDate).toLocaleDateString()} {item.slot}</td><td>{label(item.status)}</td><td><select value={item.status} onChange={(e) => update(item._id, e.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></td></tr>)}</tbody></table></div></div></section></main>;
}
