import { useState } from 'react';
import { api } from '../api';
const label = (status) => status[0].toUpperCase() + status.slice(1);
export default function Patient({ token, currentUser, doctors, appointments, refresh, onLogout }) {
  const [form, setForm] = useState({ doctorId: '', appointmentDate: '', slot: '', reason: '' }); const [error, setError] = useState('');
  const book = async (event) => { event.preventDefault(); try { setError(''); await api('/api/appointments', { token, method: 'POST', body: form }); setForm({ doctorId: '', appointmentDate: '', slot: '', reason: '' }); await refresh(); } catch (requestError) { setError(requestError.message); } };
  const active = appointments.find((item) => ['pending', 'confirmed'].includes(item.status));
  return <main className="dashboard-shell"><header className="dashboard-topbar"><div><p className="eyebrow">Patient Panel</p><h1>Welcome, {currentUser?.name}</h1></div><button className="outline-btn" onClick={onLogout}>Logout</button></header><section className="stats-grid"><article className="stat-card"><span>Your Token</span><strong>{active?.tokenNumber || '-'}</strong></article><article className="stat-card"><span>Status</span><strong>{active ? label(active.status) : 'None'}</strong></article><article className="stat-card"><span>Total Visits</span><strong>{appointments.length}</strong></article><article className="stat-card"><span>Doctors</span><strong>{doctors.length}</strong></article></section><section className="dashboard-grid"><div className="panel"><div className="panel-heading"><h2>Book Appointment</h2><p>Select doctor, time, and reason for visit.</p></div>{error && <p className="error-message">{error}</p>}<form className="stacked-form" onSubmit={book}><select value={form.doctorId} onChange={(e) => setForm({ ...form, doctorId: e.target.value })} required><option value="">Select doctor</option>{doctors.map((doctor) => <option key={doctor._id} value={doctor._id}>{doctor.name}</option>)}</select><input type="date" min={new Date().toISOString().slice(0, 10)} value={form.appointmentDate} onChange={(e) => setForm({ ...form, appointmentDate: e.target.value })} required /><input type="time" value={form.slot} onChange={(e) => setForm({ ...form, slot: e.target.value })} required /><textarea placeholder="Reason for appointment" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /><button>Book Appointment</button></form></div><div className="panel wide-panel"><div className="panel-heading"><h2>My Appointments</h2></div>{appointments.length ? <div className="queue-list">{appointments.map((item) => <div className="queue-item" key={item._id}><div className="token-box">{item.tokenNumber}</div><div className="queue-details"><strong>{item.doctorId?.name}</strong><span>{new Date(item.appointmentDate).toLocaleDateString()} at {item.slot}</span><span>{item.reason}</span></div><span className={`status-pill ${item.status}`}>{label(item.status)}</span></div>)}</div> : <div className="empty-state">No appointments booked yet.</div>}</div></section></main>;
}
